/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    screens: {
      xs: '375px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        pink: {
          DEFAULT: '#FF5E8A',
          50: '#FFF0F4',
          100: '#FFE0E9',
          200: '#FFB3C6',
          hover: '#e04070',
          glow: 'rgba(255,94,138,0.15)',
        },
        blush: '#FFB3C6',
        lavender: {
          DEFAULT: '#C8A8F0',
          light: 'rgba(200,168,240,0.3)',
          glow: 'rgba(200,168,240,0.12)',
        },
        mint: '#B8F0E4',
        yellow: {
          DEFAULT: '#FFF3B0',
          warm: '#FFE27A',
        },
        gold: '#E8C97A',
        lime: '#A8E4B4',
        coral: '#FF6B6B',
        peach: '#FFB88C',
        dark: {
          DEFAULT: '#1A1A2E',
          purple: '#2D1B69',
          plum: '#3D1A78',
        },
        midnight: '#0F0A1E',
        'deep-plum': '#2D1B69',
        'soft-rose': '#FFF0F4',
        'warm-ivory': '#FDF8F0',
        'card-bg': '#F5F0FF',
        'off-white': '#FAFAF8',
        border: 'rgba(200,168,240,0.3)',
        whatsapp: '#25D366',
      },
      fontFamily: {
        display: ['Outfit', 'sans-serif'],
        body: ['Outfit', 'sans-serif'],
        accent: ['Outfit', 'sans-serif'],
      },
      fontSize: {
        'hero': ['clamp(48px, 5vw, 72px)', { lineHeight: '1.05', letterSpacing: '-1.5px' }],
        'section-h2': ['clamp(32px, 4vw, 44px)', { lineHeight: '1.1' }],
        'card-h3': ['clamp(20px, 2vw, 24px)', { lineHeight: '1.3' }],
        'body': ['16px', { lineHeight: '1.7' }],
        'body-lg': ['18px', { lineHeight: '1.7' }],
        'caption': ['11px', { lineHeight: '1.4', letterSpacing: '2px' }],
        'nav': ['14px', { lineHeight: '1.5' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        '4xl': '80px',
        '5xl': '96px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        full: '9999px',
      },
      boxShadow: {
        'card-soft': '0 2px 12px rgba(0,0,0,0.06)',
        'card-hover': '0 12px 32px rgba(200,168,240,0.25)',
        'card-elevated': '0 8px 30px rgba(0,0,0,0.08), 0 0 0 1px rgba(200,168,240,0.1)',
        'neo': '4px 4px 0px #1A1A2E',
        'neo-hover': '2px 2px 0px #1A1A2E',
        'neo-active': '0px 0px 0px #1A1A2E',
        'glow-pink': '0 0 40px rgba(255,94,138,0.3)',
        'glow-pink-lg': '0 0 60px rgba(255,94,138,0.4)',
        'glow-lavender': '0 0 60px rgba(200,168,240,0.2)',
        'glow-lavender-lg': '0 0 80px rgba(200,168,240,0.3)',
        'input-focus': '0 0 0 3px rgba(255,94,138,0.12)',
      },
      maxWidth: {
        container: '1200px',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(40px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(-3deg)' },
          '50%': { transform: 'translateY(-14px) rotate(-3deg)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        countUp: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        spin: {
          to: { transform: 'rotate(360deg)' },
        },
        'gradient-shift': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.9)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-left': {
          from: { opacity: '0', transform: 'translateX(-30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'bounce-subtle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        'float-heart': {
          '0%': { opacity: '0', transform: 'translateY(0) scale(0.5)' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0', transform: 'translateY(-80px) scale(1)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(1)', opacity: '0.6' },
          '100%': { transform: 'scale(1.5)', opacity: '0' },
        },
      },
      animation: {
        'fade-up': 'fadeUp 0.6s ease both',
        'slide-up': 'slideUp 0.8s ease both',
        'float-a': 'float 3s ease-in-out infinite',
        'float-b': 'float 3.5s ease-in-out 0.5s infinite',
        'float-c': 'float 4s ease-in-out 1s infinite',
        marquee: 'marquee 30s linear infinite',
        shimmer: 'shimmer 2s linear infinite',
        spin: 'spin 1s linear infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        'scale-in': 'scale-in 0.5s ease both',
        'slide-in-left': 'slide-in-left 0.5s ease both',
        'slide-in-right': 'slide-in-right 0.5s ease both',
        'bounce-subtle': 'bounce-subtle 2s ease-in-out infinite',
        'pulse-slow': 'pulse-slow 3s ease-in-out infinite',
        'float-heart': 'float-heart 3s ease-in-out forwards',
        'pulse-ring': 'pulse-ring 1.5s ease-out infinite',
      },
    },
  },
  plugins: [],
};
